### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by jeanpaul-mokaza** [rengwuxian/MaterialEditText#103]
Hello, I'm getting the following error when trying to use the library on my project. I'm starting with just a simple one with floating label as follows, but I keep getting the same NoSuchFieldError.

< com.rengwuxian.materialedittext.MaterialEditText 
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:hint="Custom Floating Label Text"
app:floatingLabel="normal"
app:floatingLabelText="Label" />

I'm using gradle on Android Studio 1.0 to import the module. Below is the stack trace. Can you help please. I love this library and I was really motivated into using it. :(

java.lang.NoSuchFieldError: MaterialEditText_floatingLabelAlwaysShown
	at com.rengwuxian.materialedittext.MaterialEditText.init(MaterialEditText.java:357)
	at com.rengwuxian.materialedittext.MaterialEditText.<init>(MaterialEditText.java:280)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:375)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:100)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:172)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:132)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:400)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:332)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:332)
	at com.android.tools.idea.rendering.RenderService$3.compute(RenderService.java:575)
	at com.android.tools.idea.rendering.RenderService$3.compute(RenderService.java:564)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:564)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:691)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:604)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1900(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:546)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:541)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)

**Comment by rengwuxian** [comment]
Hi @jeanpaul-mokaza ,

Sorry for the delay reply, being a little busy these days. Have you solved this problem now?

**Comment by jeanpaul-mokaza** [comment]
Hi, not yet no. Didn't get to use it at all for lack of time. Any idea what
could be the issue?

**Comment by rengwuxian** [comment]
Where does this happen? Only preview view or also when you run the app?
