### ISSUE TITLE
app crashing on android 4.4.4 but running in 5.0 and greater need urgent help error of floatingLabel

### ISSUE THREAD

**Issue by Anto1106** [rengwuxian/MaterialEditText#282]
TAL EXCEPTION: main
                                                                                 java.lang.VerifyError: com/nineoldandroids/animation/ObjectAnimator
                                                                                     at com.rengwuxian.materialedittext.MaterialEditText.getLabelFocusAnimator(MaterialEditText.java:1257)
                                                                                     at com.rengwuxian.materialedittext.MaterialEditText.access$600(MaterialEditText.java:51)
                                                                                     at com.rengwuxian.materialedittext.MaterialEditText$3.onFocusChange(MaterialEditText.java:893)
                                                                                     at android.view.View.onFocusChanged(View.java:3885)
                                                                                     at android.widget.TextView.onFocusChanged(TextView.java:8718)
                                                                                     at android.view.View.handleFocusGainInternal(View.java:3707)
                                                                                     at android.view.View.requestFocus(View.java:5400)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2408)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2408)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2408)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2408)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2408)
                                                                                     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2452)
                                                                                     at android.view.ViewGroup.requestFocus(ViewGroup.java:2411)
                                                                                     at android.view.View.requestFocus(View.java:5350)
                                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
                                                                                     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2695)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:4987)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by Anto1106** [comment]
Error is because of app:met_floatingLabel="highlight" floating label
