### ISSUE TITLE
[issue] Rendering Problems in preview - Resources$NotFoundException for inner_components_spacing

### ISSUE THREAD

**Issue by sosite** [rengwuxian/MaterialEditText#285]
```
android.content.res.Resources$NotFoundException: Could not find dimen resource matching value 0x7F0B00AC (resolved name: inner_components_spacing) in current configuration.
   at android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:871)
   at android.content.res.Resources_Delegate.getDimensionPixelSize(Resources_Delegate.java:572)
   at android.content.res.Resources.getDimensionPixelSize(Resources.java:687)
   at android.support.v7.widget.ResourcesWrapper.getDimensionPixelSize(ResourcesWrapper.java:118)
   at com.rengwuxian.materialedittext.MaterialEditText.init(MaterialEditText.java:339)
   at com.rengwuxian.materialedittext.MaterialEditText.<init>(MaterialEditText.java:325)
```

probably here:
```java
private void init(Context context, AttributeSet attrs) {
        ...
        this.bottomSpacing = this.getResources().getDimensionPixelSize(dimen.inner_components_spacing);
        ...
}
```

**Comment by aitbaali** [comment]
same error

Android Studio 2.1.2
materialedittext:library:2.1.4

**Comment by aitbaali** [comment]
I have manage to solve this by updating my Gradle.

**Before:**
`compile 'com.rengwuxian.materialedittext:library:2.1.4'`

**Solution**
```
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```

```
dependencies {
    compile 'com.github.rengwuxian:MaterialEditText:2.1.4'
}
```

[source](https://android-arsenal.com/details/1/1085#package)
