### ISSUE TITLE
bug when click recort text after onLongClick in MaterialEditText

### ISSUE THREAD

**Issue by CaioHenriqueAndrade** [rengwuxian/MaterialEditText#356]
log is...

                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                                  at android.widget.Toast.makeText(Toast.java:433)
                                                                                  at android.widget.Toast.makeText(Toast.java:493)
                                                                                  at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:1263)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                               Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class TextView
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                  at android.widget.Toast.makeText(Toast.java:433) 
                                                                                  at android.widget.Toast.makeText(Toast.java:493) 
                                                                                  at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:1263) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7409) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                               Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x3/d=0x9a "res/color/abc_primary_text_material_dark.xml" a=3 r=0x7f0c0069}
                                                                                  at android.content.res.TypedArray.getColor(TypedArray.java:449)
                                                                                  at android.widget.TextView.<init>(TextView.java:1036)
                                                                                  at android.widget.TextView.<init>(TextView.java:957)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
                                                                                  at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
                                                                                  at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1026)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1083)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                  at android.widget.Toast.makeText(Toast.java:433) 
                                                                                  at android.widget.Toast.makeText(Toast.java:493) 
                                                                                  at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:1263) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7409) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

verify, thanks..

**Comment by varuntribe** [comment]
I am having the same issue, seems like this lib has been abandoned. Better move away from it.
