### ISSUE TITLE
NullPointerException on Layout.getLineForOffset(int) Editor.java file

### ISSUE THREAD

**Issue by jyotisakhareNira** [rengwuxian/MaterialEditText#393]
Recently migrated the project to AndroidX and below crash is happening only on Android 10 Xiaomi phones.
Please help

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
       at android.widget.Editor$ActionPinnedPopupWindow.computeLocalPosition(Editor.java:3255)
       at android.widget.Editor$PinnedPopupWindow.show(Editor.java:3577)
       at android.widget.Editor$ActionPinnedPopupWindow.show(Editor.java:3420)
       at android.widget.Editor$EmailAddPopupWindow.show(Editor.java:4944)
       at android.widget.Editor$1.run(Editor.java:1485)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7509)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)`

**Comment by olegsvs** [comment]
@jyotisakhareNira inputType is email? try https://gist.github.com/olegsvs/b86b43d317a751f77fba683e892ad787

**Comment by olegsvs** [comment]
@jyotisakhareNira inputType is email? try https://gist.github.com/olegsvs/b86b43d317a751f77fba683e892ad787

**Comment by jyotisakhare** [comment]
@olegsvs Yes. Were you able to reproduce the issue?

**Comment by olegsvs** [comment]
> @olegsvs Yes. Were you able to reproduce the issue?

Yes, analog crash report on xiaomi with miui based on android 10

**Comment by jyotisakhareNira** [comment]
@olegsvs will  include this fix for my next release and let you know whether it worked.
I do not have the xiomi device so not able to test

**Comment by jyotisakhareNira** [comment]
@olegsvs Can you please help with the steps to reproduce this issue?

**Comment by olegsvs** [comment]
> @olegsvs Can you please help with the steps to reproduce this issue?
Focus on edittext with textEmailAddress input type.

**Comment by choha** [comment]
@jyotisakhareNira has fixed it?

**Comment by jyotisakhareNira** [comment]
@choha I have replaced it with normal TextInputLayout for Email fields

**Comment by choha** [comment]
we used AppCompatEditText ，when input email also crash
