### ISSUE TITLE
java.lang.IllegalArgumentException: Layout: -36 < 0

### ISSUE THREAD

**Issue by iraycd** [rengwuxian/MaterialEditText#53]
From one of my user who is using Micromax A110:
This is the error.

java.lang.IllegalArgumentException: Layout: -36 < 0
	at android.text.Layout.<init>(Layout.java:138)
	at android.text.StaticLayout.<init>(StaticLayout.java:104)
	at android.text.StaticLayout.<init>(StaticLayout.java:90)
	at android.text.StaticLayout.<init>(StaticLayout.java:68)
	at android.text.StaticLayout.<init>(StaticLayout.java:48)
	at com.rengwuxian.materialedittext.MaterialEditText.adjustBottomLines(MaterialEditText.java:468)
	at com.rengwuxian.materialedittext.MaterialEditText.setError(MaterialEditText.java:655)
	at android.widget.TextView$1.run(TextView.java:3333)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5086)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by lukeisontheroad** [comment]
Did you a set a validateWith value? I have the same problem as soon as i do the following:

this.userInput.validateWith(new RegexpValidator("Only Integer Valid!", "\\d+"));

**Comment by iraycd** [comment]
@lukeisontheroad I have set validation.

**Comment by rengwuxian** [comment]
@iraycd Only on Micromax A110?

**Comment by iraycd** [comment]
@iraycd Yeah. It's working on Mi3 and Virtual Device. So, I think only on few phones.

**Comment by rengwuxian** [comment]
@iraycd 

1.8.1 has been released, **maybe** with a bug fix of this. (Not tested, because I don't have that kind of devices)

You can check the [latest library version](https://github.com/rengwuxian/MaterialEditText#download) now. 

_It may take several hours syncing to Maven Central._

**Comment by litrik** [comment]
I'm seeing this issue on 1.8.1 when app:helperText is set.

**Comment by iraycd** [comment]
@rengwuxian Even I don't have that. It's a problem from Client Side.

**Comment by sey** [comment]
I am able to reproduce the same error on a Nexus 5 with 1.8.1 version. It happens when I rotate the device and only if I set app:helperText as @litrik said.

**Comment by danhawkes** [comment]
@rengwuxian Hey, please have a look at #70, as I think it should fix this.

**Comment by rengwuxian** [comment]
@danhawkes 's commits has fixed this. I'll release a new version soon.

**Comment by fraisse** [comment]
cool ;-)
